### ISSUE TITLE
IPC: Lifecycle of a subnet

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/fendermint#300]
This issue collects all the pending tasks to wrap-up the implementation of the lifecycle of subnets over Fendermint.
```[tasklist]
### Tasks
- [ ] Bootstrap child subnet
- [ ] https://github.com/consensus-shipyard/fendermint/issues/172 
- [ ] https://github.com/consensus-shipyard/fendermint/issues/169
- [ ] https://github.com/consensus-shipyard/ipc-agent/issues/330
```
